### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Seyeght** [MikeLydeamore/EnderBatteries#3]
```
Time: 9/10/16 11:15 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at net.minecraftforge.common.DimensionManager.getProvider(DimensionManager.java:155)
    at com.insane.enderbatteries.TileRFTank.receiveEnergy(TileRFTank.java:89)
    at mekanism.common.util.CableUtils.emit_do_do(CableUtils.java:245)
    at mekanism.common.util.CableUtils.emit_do(CableUtils.java:209)
    at mekanism.common.util.CableUtils.emit(CableUtils.java:181)
    at mekanism.common.tile.TileEntityInductionPort.onUpdate(TileEntityInductionPort.java:68)
    at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:75)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

I'm thinking someone placed it right on the Induction Port on the Mekanism Multiblock battery structure, not sure, but it looks a lot like the crash we get when its placed right on a Ender IO Capacitor Bank, which is submitted below. As always, I can provide as much logging as you need for these errors, just hit me up on Curse/Discord to let me know what you need.

```
Time: 8/30/16 11:04 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at net.minecraftforge.common.DimensionManager.getProvider(DimensionManager.java:155)
    at com.insane.enderbatteries.TileRFTank.receiveEnergy(TileRFTank.java:89)
    at crazypants.enderio.power.EnergyReceiverPI.recieveEnergy(EnergyReceiverPI.java:66)
    at crazypants.enderio.machine.capbank.network.CapBankNetwork.sendPowerTo(CapBankNetwork.java:293)
    at crazypants.enderio.machine.capbank.network.CapBankNetwork.transmitEnergy(CapBankNetwork.java:268)
    at crazypants.enderio.machine.capbank.network.CapBankNetwork.doNetworkTick(CapBankNetwork.java:224)
    at crazypants.enderio.machine.capbank.network.CapBankNetwork.access$100(CapBankNetwork.java:34)
    at crazypants.enderio.machine.capbank.network.CapBankNetwork$TickReciever.tickEnd(CapBankNetwork.java:552)
    at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:59)
    at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:47)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_227_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Seyeght** [comment]
Another crash, this time with a BigReactor Power tap

```
Time: 9/14/16 2:11 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at net.minecraftforge.common.DimensionManager.getProvider(DimensionManager.java:155)
    at com.insane.enderbatteries.TileRFTank.receiveEnergy(TileRFTank.java:89)
    at erogenousbeef.bigreactors.common.multiblock.tileentity.TileEntityReactorPowerTap.onProvidePower(TileEntityReactorPowerTap.java:101)
    at erogenousbeef.bigreactors.common.multiblock.MultiblockReactor.updateServer(MultiblockReactor.java:371)
    at erogenousbeef.core.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:451)
    at erogenousbeef.core.multiblock.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:79)
    at erogenousbeef.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:26)
    at erogenousbeef.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:20)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_598_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by Seyeght** [comment]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 11/9/16 2:17 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at net.minecraftforge.common.DimensionManager.getProvider(DimensionManager.java:155)
    at com.insane.enderbatteries.TileRFTank.receiveEnergy(TileRFTank.java:89)
    at com.rwtema.extrautils.tileentity.generators.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:246)
    at com.rwtema.extrautils.tileentity.generators.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:223)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- Head --
Stacktrace:
    at net.minecraftforge.common.DimensionManager.getProvider(DimensionManager.java:155)
    at com.insane.enderbatteries.TileRFTank.receiveEnergy(TileRFTank.java:89)
    at com.rwtema.extrautils.tileentity.generators.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:246)
    at com.rwtema.extrautils.tileentity.generators.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:223)
    at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
    Name: extrautils:generatorlava // com.rwtema.extrautils.tileentity.generators.TileEntityGeneratorMagma
    Block type: ID #1637 (tile.extrautils:generator.8 // com.rwtema.extrautils.tileentity.generators.BlockGenerator)
    Block data value: 2 / 0x2 / 0b0010
    Block location: World: (-1886,86,466), Chunk: (at 2,5,2 in -118,29; contains blocks -1888,0,464 to -1873,255,479), Region: (-4,0; contains chunks -128,0 to -97,31, blocks -2048,0,0 to -1537,255,511)
    Actual block type: ID #1637 (tile.extrautils:generator.8 // com.rwtema.extrautils.tileentity.generators.BlockGenerator)
    Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

**Comment by Seyeght** [comment]
Issue was fixed in earlier version by adding a dimension check.
